export const CHAT_SOCKET_MUTATION = 'chatSocketMutation'
export const CURRENT_CHAT_MUTATION = 'currentChatMutation'
export const USER_MUTATION = 'userMutation'
export const FRIEND_LIST_MUTATION = 'friendListMutation'
export const ONLINE_MUTATION = 'onlineMutation'
