export const CHAT_SOCKET_MUTATION = 'chatSocketMutation'
export const CURRENT_CHAT_MUTATION = 'currentChatMutation'
export const USER_MUTATION = 'userMutation'
export const FRIEND_LIST_MUTATION = 'friendListMutation'
export const ONLINE_MUTATION = 'onlineMutation'
export const ADD_MESSAGE_MUTATION = 'addMessageMutation'
export const SORT_FRIEND_LIST_MUTATION = 'sortFriendListMutation'
